# Generated by Django 5.2.15 on 2026-06-11 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0001_initial'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('retirada', 'Retirada'), ('devolucao', 'Devolucao'), ('panico', 'Panico'), ('autorizacao', 'Autorizacao'), ('atraso', 'Atraso'), ('status_slot', 'Status do slot'), ('erro', 'Erro'), ('negado', 'Negado')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('chave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='chaves.chave')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='salas.sala')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
