# Generated by Django 5.2.15 on 2026-06-11 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['timestamp'], name='idx_evento_timestamp'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['chave', 'timestamp'], name='idx_evento_chave_time'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['usuario', 'timestamp'], name='idx_evento_usuario_time'),
        ),
    ]
