# Generated by Django 5.2.15 on 2026-06-11 02:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True)),
                ('andar', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)])),
                ('numero', models.CharField(max_length=4)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('tipo_sala', models.CharField(choices=[('LAB', 'Laboratorio'), ('SALA', 'Sala de Aula'), ('COZINHA', 'Cozinha'), ('AUDITORIO', 'Auditorio')], default='SALA', max_length=10)),
            ],
        ),
    ]
