# Generated by Django 5.2.15 on 2026-06-11 02:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valida_de', models.DateTimeField(default=django.utils.timezone.now)),
                ('valida_ate', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('motivo', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
