# Generated by Django 5.2.15 on 2026-06-11 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizacoes', '0001_initial'),
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='concedida_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_concedidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to='salas.sala'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='autorizacao',
            index=models.Index(fields=['usuario', 'ativa'], name='idx_aut_usuario_ativa'),
        ),
    ]
