# Generated by Django 5.2.15 on 2026-06-11 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
