# Generated by Django 5.2.15 on 2026-06-11 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feito_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chaves.chave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('operacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operacoes.operacao')),
                ('retirado_em', models.DateTimeField(auto_now_add=True)),
                ('devolvido_em', models.DateTimeField(blank=True, null=True)),
                ('limite_devolucao', models.DateTimeField(blank=True, null=True)),
                ('atraso_registrado', models.BooleanField(default=False)),
            ],
            bases=('operacoes.operacao',),
        ),
    ]
