# Generated by Django 5.2.15 on 2026-06-11 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucao',
            name='emprestimo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='devolucao', to='operacoes.emprestimo'),
        ),
    ]
