# Generated by Django 5.2.15 on 2026-06-11 02:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='O numero deve conter 4 digitos.', regex='^\\d{4}$')])),
                ('rfid_tag', models.CharField(help_text='Hash da tag RFID', max_length=64, unique=True)),
                ('slot_x', models.PositiveSmallIntegerField()),
                ('slot_y', models.PositiveSmallIntegerField()),
                ('slot_ocupado', models.BooleanField(default=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('emprestada', 'Emprestada'), ('em_transito', 'Em transito'), ('manutencao', 'Manutencao')], db_index=True, default='disponivel', max_length=20)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaves', to='salas.sala')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
                'unique_together': {('sala', 'numero')},
            },
        ),
    ]
